name: Deploy Firebase (functions + rules)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Build functions
        working-directory: functions
        run: |
          npm install --no-audit --no-fund
          npm run build

      - name: Deploy Firestore rules
        run: firebase deploy --project ${{ secrets.GCP_PROJECT_ID }} --only firestore:rules
      - name: Set Functions runtime config (easyfin.folder_id)

        run: firebase functions:config:set easyfin.folder_id="${{ secrets.EASYFIN_FOLDER_ID }}" --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy Cloud Functions
        env:
          EASYFIN_FOLDER_ID: ${{ secrets.EASYFIN_FOLDER_ID }}
        run: firebase deploy --project ${{ secrets.GCP_PROJECT_ID }} --only functions
